### ISSUE TITLE
Force convert for near-black colors

### ISSUE THREAD

**Issue by markroepke** [nsgrantham/ggdark#2]
Hi Neal,

This is a great package. I have an enhancement suggestion relating to:

https://github.com/nsgrantham/ggdark/blob/e85b4dabe367352f6c792fbc778725f67af62685/R/dark_mode.R#L36

I suggest near-black be returned as `TRUE` from this line, as well. Examples of these colors are: 

- ![#330000](https://placehold.it/15/330000/000000?text=+) `#330000`
- ![#00004d](https://placehold.it/15/00004d/000000?text=+) `#00004d`
- ![#1a0d00](https://placehold.it/15/1a0d00/000000?text=+) `#1a0d00`

None of the above colors would force color inversion in the above line, but I think they probably should.

---

Rather than list all of these possible colors in the `c("black", "#000000")` vector, I am proposing something like the following:

```r
too_dark <- function(color) {
  rgb <- col2rgb(color)[,1]
  dark_rtg <- sum(c(0.299, 0.587, 0.114) * rgb)
  dark_rtg < 25
}
```

This snippet accepts a color (by name or hex) and returns a logical value indicating whether or not the color is too dark. This could be applied across the `geoms[["GeomPoint"]]$default_aes$colour` vector to determine if any of the values are too dark.

As a note, the above formula is an [International Telecommunication Union standard](https://www.itu.int/rec/R-REC-BT.601) for Luma.

---

I am happy to implement this in a pull request, but I don't see a `CONTRIBUTING.md` or similar file anywhere in your repository. Let me know if you think this is a good idea and, if so, any specifics you'd like me to apply in my pull request.

**Comment by nsgrantham** [comment]
Hi Mark,

I'm glad you're enjoying ggdark!

As you have found, geom fill and color/colour inversion in ggdark is not ideal. In the current version of ggplot2, 3.1.0, the only way (AFAICT) to manipulate the geom aesthetics is by globally redefining their default values. This leads to the awkward behavior where calling a dark theme for the first time inverts the default fill and color/colour values of all geoms in the loaded namespaces, rather than inverting only the values of geoms used in the ggplot2 object to which the dark theme is applied. This in turn leads to the `geoms_are_dark` check within `dark_mode()` which makes sure it doesn't need to perform the inversion again after it has already happened. If the default geom point color/colour is no longer "black" (its default value in ggplot2) then the geoms were probably inverted and shouldn't be changed again (unless `force_geom_inverts = TRUE`). Is this a hacky way to address the problem? You bet. :)

Thankfully, an open PR on ggplot2, https://github.com/tidyverse/ggplot2/pull/2749, will allow geom defaults to be defined as part of the theme. This change will simplify ggdark quite a bit because inverting geom defaults will behave just the same as inverting theme elements. There will no longer be a need to change the global geom defaults, which avoids all the problems mentioned so far. 

All this is to say, you are correct in that near-dark values in geom point should probably trigger `invert_geom_defaults()`. However, I'm afraid an enhancement like you have suggested could introduce more complexity than this problem frankly deserves! I'm happy to accept a PR if you find you can strike a nice balance. I think the true fix will come in an upcoming ggplot2 release (hopefully 3.2.0?), but no word yet on when that's likely to happen.

P.S. Thanks for pointing out that I'm missing a `CONTRIBUTING.md`, I'll change that.

**Comment by markroepke** [comment]
Thanks for letting me know about the ggplot2 issue - that's a great idea. I agree that this should solve this issue. Unfortunately, I am looking for a more immediate fix due to near-black branding in some projects I'm working on.

I can always use the snippet above and in my own fork of your project. However, I figure others may also need this more immediately so I will try to simplify the above suggestion and submit a pull request.

Out of curiosity, what did you feel was too complex about the above proposed implementation? I want to be sure to address your concerns.

**Comment by nsgrantham** [comment]
I don't think your proposed implementation is too complex. I'm only speaking to the potentially larger problem of devoting time and attention to workarounds that will be rendered obsolete in the near future. However, your use case sounds reasonable, and not unlike what other users may be facing, so I look forward to your PR.

**Comment by markroepke** [comment]
Nathan, upon further review this doesn't address my concern - I should've reviewed the ggdark source code in more detail. I will close the issue and wait for ggplot2's update to set default geom aesthetics via a theme.

Thanks for talking through this and for your time.

**Comment by nsgrantham** [comment]
No problem Mark! Thanks for the discussion. I hope you find a suitable fix to your problem.
