### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by edawson** [nsgrantham/ggdark#7]
Howdy,

   This is an awesome package - thanks for providing such a simple API for making dark-theme plots! I'd like to make some modifications on top of the ggdark themes and contribute any that are useful back upstream. Would you consider relicensing the repo under an [open source friendly license](https://opensource.org/licenses)? I won't advise on which license to choose (that's something for you to decide), but something more permissive would encourage contributions, and a Citation / Contributing guide could help ensure you still got proper credit from the community. 

Cheers,
  Eric

**Comment by nsgrantham** [comment]
Hi Eric,

The package is already MIT-licensed and has been since the beginning. R packages are a little strange in that you specify the license in DESCRIPTION with `License: MIT + file LICENSE` where LICENSE contains my name and the copyright year.

I'll add a Citation / Contributing guide, that's a good idea.

Thanks,
Neal

**Comment by edawson** [comment]
Ah, interesting! I totally didn't know about the R licensing quirk. Thanks Neal!
